# # # # # # # #
#  chiyodad   #
# # # # # # # #

# Basic
name:               "chiyodad"

# URL
baseurl:            ""
#baseurl:           "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           redcarpet

# Navigation
nav:
  - name:           "about"
    href:           "//chiyodad.github.io/about"
  - name:           "tomato"
    href:           "//chiyodad.github.io/tomato"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
