# # # # # # # #
#  chiyodad   #
# # # # # # # #

# Basic
name: chiyodad
safe: true
lsi: false

# URL
baseurl:            "/blog"
#baseurl:           "" #For Root Domain
#permalink:          /:year/:month/:day/:title.html
permalink: pretty

# Markdown
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# Navigation
nav:
  - name:           "about"
    href:           "//chiyodad.github.io/about"
  - name:           "blog"
    href:           "//chiyodad.github.io/blog"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
