# # # # # # # #
#  chiyodad   #
# # # # # # # #

# Basic
name: chiyodad
safe: true
lsi: false

# URL
baseurl:            ""
#baseurl:           "" #For Root Domain
#permalink:          /:year/:month/:day/:title.html
permalink: pretty

# Markdown
markdown:  kramdown
highliter: rouge

# Navigation
nav:
  - name:           "about"
    href:           "//chiyodad.github.io/about"
  - name:           "tomato"
    href:           "//chiyodad.github.io/tomato"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
