# # # # # # # #
#  chiyodad   #
# # # # # # # #

# Basic
title: fying in the dream
name: chiyodad
safe: true
pygments: true
lsi: false
email: chiyodad@yahoo.com
url: "http://chiyodad.com" # the base hostname & protocol for your site
twitter_username: chiyodad
github_username:  chiyodad


# URL
baseurl:            ""
#baseurl:           "" #For Root Domain
permalink:          /blog/:year/:month/:day/:title.html
#permalink: pretty

# Markdown
kramdown:
  input: GFM
  # syntax_highlighter: rouge


# Navigation
nav:
  - name:           "about"
    href:           "/about"
  - name:           "blog"
    href:           "/blog"
  - name:           "tomato"
    href:           "/tomato"

# Sass
sass:
  sass_dir: _sass
  style: compressed  

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
layout:       "post"

paginate: 4

author: chiyodad

gems: [jekyll-paginate]
